encoding: UTF-8
permalink: /:title/
title: Zakuan Efandi - Personal Portfolio
description: Personal Portfolio
author:
    first_name: Zakuan
    last_name: Efandi
    admin:
        name: Zakuan Efandi
        email: m.zakuan.efandi@gmail.com
        web: 
url:https://zakuanefandi.github.io/